name: CI Test

on: [ push, pull_request ]

jobs:
    bats:
        name: Bash Automated Testing System
        runs-on: ubuntu-latest
        container: bats/bats:latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run Bash Automated Testing System
                run: LC_ALL=C.UTF-8 LANGUAGE=C.UTF-8 bats --verbose-run --recursive ./test/
